CREATE TABLE IF NOT EXISTS Director(
	id SERIAL PRIMARY KEY,
	name TEXT NOT NULL,
	country TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS Star(
	id SERIAL PRIMARY KEY,
	name TEXT NOT NULL,
	DOB DATE NOT NULL
);
CREATE TABLE IF NOT EXISTS Writer(
	id SERIAL PRIMARY KEY,
	name TEXT NOT NULL,
	email TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS Film(
	id SERIAL PRIMARY KEY,
	title TEXT NOT NULL,
	director_id INT NOT NULL,
	star_id INT NOT NULL,
	writer_id INT NOT NULL,
	release_year INT NOT NULL,
	genre TEXT NOT NULL,
	score INT NOT NULL CHECK (score >=0 AND score<=10),
	CONSTRAINT fk_director
		FOREIGN KEY (director_id)
			REFERENCES Director(id),
	CONSTRAINT fk_star
		FOREIGN KEY (star_id)
			REFERENCES Star(id),
	CONSTRAINT fk_writer
		FOREIGN KEY (writer_id)
			REFERENCES Writer(id)
);