
INSERT INTO director (name, country) VALUES
('Stanley Kubrick','USA'),
('George Lucas','USA'),
('Robert Mulligan','USA'),
('James Cameron','Canada'),
('David Lean','UK'),
('Anthony Mann','USA'),
('Theodoros Angelopoulos','Greece'),
('Paul Verhoeven','Netherlands'),
('Krzysztof Kieslowski','Poland'),
('Jean-Paul Rappeneau','France');


INSERT INTO writer (name, email) VALUES
('Arthur C Clarke','arthur@clarke.com'),
('George Lucas','george@email.com'),
('Harper Lee','harper@lee.com'),
('James Cameron','james@cameron.com'),
('Boris Pasternak','boris@boris.com'),
('Frederick Frank','fred@frank.com'),
('Theodoros Angelopoulos','theo@angelopoulos.com'),
('Erik Hazelhoff Roelfzema','erik@roelfzema.com'),
('Krzysztof Kieslowski','email@email.com'),
('Edmond Rostand','edmond@rostand.com');

INSERT INTO star (name, dob) VALUES
('Keir Dullea','1936-05-30'),
('Mark Hamill','1951-09-25'),
('Gregory Peck','1916-04-05'),
('Leonardo DiCaprio','1974-11-11'),
('Julie Christie','1940-04-14'),
('Charlton Heston','1923-10-04'),
('Manos Katrakis','1908-08-14'),
('Rutger Hauer','1944-01-23'),
('Juliette Binoche','1964-03-09'),
('Gerard Depardieu','1948-12-27');

INSERT INTO film (title, year, genre, score, director_id, writer_id) VALUES
('2001: A Space Odyssey',1968,'Science Fiction',10,
(SELECT director_id FROM director WHERE name='Stanley Kubrick' AND country='USA'),
(SELECT writer_id   FROM writer   WHERE name='Arthur C Clarke')),
('Star Wars: A New Hope',1977,'Science Fiction',7,
(SELECT director_id FROM director WHERE name='George Lucas' AND country='USA'),
(SELECT writer_id   FROM writer   WHERE name='George Lucas')),
('To Kill A Mockingbird',1962,'Drama',10,
(SELECT director_id FROM director WHERE name='Robert Mulligan' AND country='USA'),
(SELECT writer_id   FROM writer   WHERE name='Harper Lee')),
('Titanic',1997,'Romance',5,
(SELECT director_id FROM director WHERE name='James Cameron' AND country='Canada'),
(SELECT writer_id   FROM writer   WHERE name='James Cameron')),
('Dr Zhivago',1965,'Historical',8,
(SELECT director_id FROM director WHERE name='David Lean' AND country='UK'),
(SELECT writer_id   FROM writer   WHERE name='Boris Pasternak')),
('El Cid',1961,'Historical',6,
(SELECT director_id FROM director WHERE name='Anthony Mann' AND country='USA'),
(SELECT writer_id   FROM writer   WHERE name='Frederick Frank')),
('Voyage to Cythera',1984,'Drama',8,
(SELECT director_id FROM director WHERE name='Theodoros Angelopoulos' AND country='Greece'),
(SELECT writer_id   FROM writer   WHERE name='Theodoros Angelopoulos')),
('Soldier of Orange',1977,'Thriller',8,
(SELECT director_id FROM director WHERE name='Paul Verhoeven' AND country='Netherlands'),
(SELECT writer_id   FROM writer   WHERE name='Erik Hazelhoff Roelfzema')),
('Three Colours: Blue',1993,'Drama',8,
(SELECT director_id FROM director WHERE name='Krzysztof Kieslowski' AND country='Poland'),
(SELECT writer_id   FROM writer   WHERE name='Krzysztof Kieslowski')),
('Cyrano de Bergerac',1990,'Historical',9,
(SELECT director_id FROM director WHERE name='Jean-Paul Rappeneau' AND country='France'),
(SELECT writer_id   FROM writer   WHERE name='Edmond Rostand'));

INSERT INTO film_star (film_id, star_id) VALUES
((SELECT film_id FROM film WHERE title='2001: A Space Odyssey' AND year=1968),
(SELECT star_id FROM star WHERE name='Keir Dullea' AND dob='1936-05-30')),
((SELECT film_id FROM film WHERE title='Star Wars: A New Hope' AND year=1977),
(SELECT star_id FROM star WHERE name='Mark Hamill' AND dob='1951-09-25')),
((SELECT film_id FROM film WHERE title='To Kill A Mockingbird' AND year=1962),
(SELECT star_id FROM star WHERE name='Gregory Peck' AND dob='1916-04-05')),
((SELECT film_id FROM film WHERE title='Titanic' AND year=1997),
(SELECT star_id FROM star WHERE name='Leonardo DiCaprio' AND dob='1974-11-11')),
((SELECT film_id FROM film WHERE title='Dr Zhivago' AND year=1965),
(SELECT star_id FROM star WHERE name='Julie Christie' AND dob='1940-04-14')),
((SELECT film_id FROM film WHERE title='El Cid' AND year=1961),
(SELECT star_id FROM star WHERE name='Charlton Heston' AND dob='1923-10-04')),
((SELECT film_id FROM film WHERE title='Voyage to Cythera' AND year=1984),
(SELECT star_id FROM star WHERE name='Manos Katrakis' AND dob='1908-08-14')),
((SELECT film_id FROM film WHERE title='Soldier of Orange' AND year=1977),
(SELECT star_id FROM star WHERE name='Rutger Hauer' AND dob='1944-01-23')),
((SELECT film_id FROM film WHERE title='Three Colours: Blue' AND year=1993),
(SELECT star_id FROM star WHERE name='Juliette Binoche' AND dob='1964-03-09')),
((SELECT film_id FROM film WHERE title='Cyrano de Bergerac' AND year=1990),
(SELECT star_id FROM star WHERE name='Gerard Depardieu' AND dob='1948-12-27'));
